# Site settings
title: Late Night Swift
description: A Swift and iOS Development Blog
url: "http://www.latenightswift.com"
twitter_url: https://twitter.com/latenightswift_
github_url: https://github.com/latenightswift
subscribe_url: https://mailchimp.com

# Build Settings
markdown: kramdown
google_analytics: UAâ€”XXXXXXXX-X
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - design
